### PR TITLE
Converted statefullWidget to statelessWidget

### PR DESCRIPTION
**Pull request by Abhishek01039**

### CODE REVIEW

**Comment by Abhishek01039** [comment]
@domesticmouse 
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
Sorry, I came to know that we need stateful widget here.

**Comment by Abhishek01039** [comment]
Hello @domesticmouse 
can I update the version of Provider?
Thanks

**Comment by domesticmouse** [comment]
Hey @Abhishek01039, this repo is deprecated. Please see https://github.com/flutter/codelabs/tree/master/cupertino_store for the new repo. Thanks!

**Pull request closed without merging**
